#! /usr/bin/env python

import sys,os
sys.path.append(os.pardir)
import subprocess

from libs import Channel

def ask_file_access(pid, pipe_path):
    ch = Channel.MogamiChanneltoAskAP(pipe_path)
    ap_list = ch.file_access_req(pid)
    return ap_list

def exec_with_file_access(cmd, pipe_path):
    ret = subprocess.Popen(cmd)
    pid = ret.pid
    ret.wait()
    return ask_file_access(pid, pipe_path)

if __name__ == '__main__':
    if len(sys.argv) < 2:
        sys.exit("Usage: %s [cmd_to_execute]")
    # remove the first argument of cmd
    sys.argv.pop(0)
    ap = exec_with_file_access(sys.argv, "/tmp/mogami_ap")
    print ap
